project:
  type: book
  output-dir: docs

book:
  title: "The Practice R Tutorials"
  author: "Edgar J. Treischl"
  date: last-modified
  chapters:
    - index.qmd
    - chapter_02.qmd
    - chapter_03.qmd
    - chapter_04.qmd
    - chapter_05.qmd
    - chapter_06.qmd
    - chapter_07.qmd
    - chapter_08.qmd
    - chapter_10.qmd
    - chapter_11.qmd
    - references.qmd
  navbar:
    right:
      - icon: github
        href: https://github.com/edgar-treischl/PracticeR_Tutorials
        aria-label: GitHub

cover-image: cover.jpg
bibliography: PracticeR_FINAL.bib

format:
  html:
    theme: litera
    include-in-header: 
      - progress-bar.html
  pdf:
    documentclass: scrreprt
    highlight-style: kate


