project:
  type: book
  output-dir: docs

book:
  title: "Practice R: Tutorials"
  author: "Edgar J. Treischl"
  date: last-modified
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  navbar:
    right:
      - icon: github
        href: https://github.com/edgar-treischl/Pythoneer
        aria-label: GitHub

cover-image: cover.png
bibliography: references.bib

format:
  html:
    theme: litera
    include-in-header: 
      - progress-bar.html
  pdf:
    documentclass: scrreprt
    highlight-style: kate


